/def -i -h'SEND {aff} *' command_aff = affirmative %-1
/def -i -h'SEND {ali} *' command_ali = cast detect alignment at %-1
/def -i -h'SEND {bcry} *' command_bcry = use battlecry at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury at %-1
/def -i -h'SEND {bl} *' command_bl = use 'bloodlust' %-1
/def -i -h'SEND {burn}' command_burn = light torch;;use looting and burning
/def -i -h'SEND {camp}' command_camp = use camping
/def -i -h'SEND {c} *' command_c = cast 'hoar frost' %-1;;alias tgt %-1
/def -i -h'SEND {con} *' command_con = use 'consider' %-1
/def -i -h'SEND {cot} *' command_cot = cast curse of tarmalen at %-1
/def -i -h'SEND {dg} *' command_dg = dig grave %-1
/def -i -h'SEND {ebl} *' command_ebl = cast earth blood at %-1
/def -i -h'SEND {epow} *' command_epow = cast earth power at %-1
/def -i -h'SEND {es} *' command_es = cast earth skin at %-1
/def -i -h'SEND {fa} *' command_fa = use first aid at %-1
/def -i -h'SEND {flx} *' command_flx = cast 'flex shield' %-1%;flex %-1
/def -i -h'SEND {g} *' command_g = cast gem fire at use gem %-1
/def -i -h'SEND {gspam}' command_gspam = ghost accept rais/ress/body/reinc from noitatohtori
/def -i -h'SEND {h} *' command_h = cast cure loght wounds at thiamin %-1
/def -i -h'SEND {lotto}' command_lotto = winnings;;15 ticket 2 7 13
/def -i -h'SEND {otalily}' command_otalily = use ceremony;;open m;;get kukka from m;;get water lily from kukka;;put kukka in m;;close m
/def -i -h'SEND {pool}' command_pool = grep 'Thiamin' list+;;grep 'Thiamin' list-
/def -i -h'SEND {poster}' command_poster = tell damogran poster;;donate noeq;;rip poster;;donate noeq;;raha
/def -i -h'SEND {pp}' command_pp = peer e;;peer ne;;peer w;;peer sw
/def -i -h'SEND {ra} *' command_ra = tell %-1 transfer 10k, die and accept %-1
/def -i -h'SEND {raha}' command_raha = put mithril in purse;;put batium in purse;;put anipium in purse;;put platinum in purse;;put gold in purse;;deposit;;withdraw all;;put gold in purse
/def -i -h'SEND {roomdown}' command_roomdown = door down open;;down;;door up locked
/def -i -h'SEND {roomup}' command_roomup = door up open;;up;door down locker
/def -i -h'SEND {sense}' command_sense = sensecharge staff
/def -i -h'SEND {sosu}' command_sosu = show summary
/def -i -h'SEND {sp}' command_sp = show spells
/def -i -h'SEND {ss}' command_ss = show skills
/def -i -h'SEND {t} *' command_t = tell %-1
/def -i -h'SEND {wf} *' command_wf = cast wither flesh at %-1
/def -i -h'SEND {ws} *' command_ws = cast 'summon' %-1;;wanted got %-1;;tell %-1 gotcha! %-1
/def -i -h'SEND {tr} *' command_tr = trivia $* %-1
/def -i -h'SEND {h} *' command_h = cast cure light wounds at thiamin %-1
/def -i -h'SEND {con} *' command_con = use consider at %-1
/def -i -h'SEND {bcry} *' command_bcry = use battlecry at %-1
/def -i -h'SEND {newbie} *' command_newbie = bs %-1
/def -i -h'SEND {wind} *' command_wind = cast drying wind %-1
/def -i -h'SEND {safka} *' command_safka = safka+ say %-1
/def -i -h'SEND {ita} *' command_ita = cast inquiry to ahm at %-1
/def -i -h'SEND {ra} *' command_ra = tell %-1 transfer (10k), die, accept %-1
/def -i -h'SEND {dp} *' command_dp = cast drain pool at amount %-1
/def -i -h'SEND {con} *' command_con = use consider at %-1
/def -i -h'SEND {pc} *' command_pc = party create บบนบนบนบ %-1
/def -i -h'SEND {c} *' command_c = use stab at %-1
/def -i -h'SEND {con} *' command_con = use consider at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury at %-1
/def -i -h'SEND {con} *' command_con = use consider at %-1
/def -i -h'SEND {con} *' command_con = use consider at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury %-1
/def -i -h'SEND {con} *' command_con = use consider %-1
/def -i -h'SEND {con} *' command_con = use consider at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury at %-1
/def -i -h'SEND {f} *' command_f = finger $*;;countries $*;;atlas find $* %-1
/def -i -h'SEND {mm} *' command_mm = cast 'magic missile' %-1
/def -i -h'SEND {mm} *' command_mm = cast magic missile at %-1
/def -i -h'SEND {aura} *' command_aura = cast energy aura %-1
/def -i -h'SEND {cb} *' command_cb = cast channelball at %-1
/def -i -h'SEND {dr} *' command_dr = cast drain room %-1
/def -i -h'SEND {cu} *' command_cu = cast channelburn at %-1
/def -i -h'SEND {dcc} *' command_dcc = dcc+ say %-1
/def -i -h'SEND {cs} *' command_cs = use prayer to destruction at spell %-1
/def -i -h'SEND {cs} *' command_cs = check supply %-1
/def -i -h'SEND {de} *' command_de = cast drain enemy at %-1
/def -i -h'SEND {ra} *' command_ra = cast replenish ally at %-1
/def -i -h'SEND {fabs} *' command_fabs = cast force absorption at %-1
/def -i -h'SEND {sum} *' command_sum = cast summon at %-1
/def -i -h'SEND {relo} *' command_relo = cast relocate at %-1
/def -i -h'SEND {aoa} *' command_aoa = @@party say AOA -> %-1%;cast armour of aether at %-1
/def -i -h'SEND {tele} *' command_tele = cast teleport without error %-1
/def -i -h'SEND {dmp} *' command_dmp = cast dispel magical protection at %-1
/def -i -h'SEND {relo} *' command_relo = cast relocate at $*;;zoom $* %-1
/def -i -h'SEND {mm} *' command_mm = cast magic missile at %-1
/def -i -h'SEND {nf} *' command_nf = cast neutralize field %-1
/def -i -h'SEND {g} *' command_g = unlock door with key to freezer;;sw;;lock door with key to freezer;;neener aceduck %-1
/def -i -h'SEND {g} *' command_g = unlock door with key to freezer;;sw;;lock door with key to freezer;;neener aceduck %-1
/def -i -h'SEND {rd} *' command_rd = cast resisd dispel at %-1
/def -i -h'SEND {clw} *' command_clw = cast cure light wounds at $* %-1
/def -i -h'SEND {kl} *' command_kl = kirahvi+ say lotto %-1
/def -i -h'SEND {mm} *' command_mm = cast 'magic missile' %-1
/def -i -h'SEND {call} *' command_call = docall %-1
/def -i -h'SEND {co} *' command_co = cast channelbolt at %-1
/def -i -h'SEND {co} *' command_co = cast channelbolt at %-1
/def -i -h'SEND {co} *' command_co = cast channelbolt at %-1
/def -i -h'SEND {iw} *' command_iw = cast iron will at nt %-1
/def -i -h'SEND {iw} *' command_iw = cast iron will at %-1
/def -i -h'SEND {sum} *' command_sum = cast summon at $*;;tell $* Trying to summon you... %-1
/def -i -h'SEND {hrw} *' command_hrw = hardware+ say %-1
/def -i -h'SEND {man} *' command_man = help %-1
/def -i -h'SEND {W} *' command_W = @W;look %-1
/def -i -h'SEND {ulos} *' command_ulos = door south open;;s;;door north locked;;s;;s;;s;;u;;w;;w %-1
/def -i -h'SEND {ulos} *' command_ulos = door south open;;s;;door north locked;;s;;s;;s;;u;;w;;w %-1
/def -i -h'SEND {sisaan} *' command_sisaan = e;;e;;d;;n;;n;;n;;door north open;;n;;door south locked %-1
/def -i -h'SEND {k} *' command_k = use kick at box %-1
/def -i -h'SEND {k} *' command_k = use kick at box %-1
/def -i -h'SEND {hw} *' command_hw = cast heavy weight at $* %-1
/def -i -h'SEND {hw} *' command_hw = cast heavy weight at $* %-1
/def -i -h'SEND {gspam} *' command_gspam = ghost accept rais/ress/body/reinc from noitatohtori %-1
/def -i -h'SEND {us} *' command_us = cast unstun at $* %-1
/def -i -h'SEND {mm} *' command_mm = cast magic missile at %-1
/def -i -h'SEND {ext} *' command_ext = extract highsteel disc from aoa %-1
/def -i -h'SEND {mb} *' command_mb = cast mind blast at %-1
/def -i -h'SEND {mm} *' command_mm = cast magic missile at %-1
/def -i -h'SEND {ms} *' command_ms = cast mindseize at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury at %-1
/def -i -h'SEND {bf} *' command_bf = use bladed fury at %-1
/def -i -h'SEND {r1} *' command_r1 = open raha;;put mithril,batium,platinum,anipium to raha;;la raha;;close raha %-1
/def -i -h'SEND {f} *' command_f = finger $*;;;;countries $*;;;;atlas find $* %-1
/def -i -h'SEND {f} *' command_f = finger $*;;;;countries $*;;;;atlas find $* %-1
/def -i -h'SEND {lvl} *' command_lvl = grep level finger $* %-1
/def -i -h'SEND {nerds} *' command_nerds = who %-1
/def -i -h'SEND {quit} *' command_quit = save;ld %-1
/def -i -h'SEND {aa} *' command_aa = cast acid arrow at %-1
/def -i -h'SEND {lotto} *' command_lotto = winnings;;;;15 ticket 2 7 13 %-1
/def -i -h'SEND {mf} *' command_mf = mfinger %-1
/def -i -h'SEND {olympos} *' command_olympos = goto /ncity/olympos(1,11,0) %-1
/def -i -h'SEND {olympos} *' command_olympos = goto /ncity/olympos(1,11,0) %-1
/def -i -h'SEND {toss} *' command_toss = call me:$1 self_destruct %-1
/def -i -h'SEND {toss} *' command_toss = call me:$1 self_destruct %-1
/def -i -h'SEND {f} *' command_f = finger $*;;;;countries $*;;;;atlas find $* %-1
/def -i -h'SEND {f} *' command_f = mfinger $*;;countries $*;;atlas find $* %-1
/def -i -h'SEND {f} *' command_f = mfinger $*;;countries $*;;atlas find $* %-1
/def -i -h'SEND {whosolo} *' command_whosolo = grep -v < who mort $* %-1
/def -i -h'SEND {po} *' command_po = kirahvi+ say <p>: $* %-1
/def -i -h'SEND {po} *' command_po = kirahvi+ say <p>: %-1
/def -i -h'SEND {hfr} *' command_hfr = emoteto friends cheerfully waves and says 'hello'. %-1
/def -i -h'SEND {wizcast} *' command_wizcast = 'call /obj/spells/$1 do_spell_effect find_player("kimvais"),present("$-2",environment(find_player("kimvais"))) %-1
/def -i -h'SEND {wizcast} *' command_wizcast = call /obj/spells/$1 do_spell_effect find_player("kimvais"),present("$-2",environment(find_player("kimvais"))) %-1
/def -i -h'SEND {wizcast} *' command_wizcast = call /obj/spells/$1 do_spell_effect find_player("kimvais"),present("$-2",environment(find_player("kimvais"))) %-1
/def -i -h'SEND {wizcast} *' command_wizcast = call /obj/spells/$1 do_spell_effect find_player("kimvais"),present("$-2",environment(find_player("kimvais"))) %-1
/def -i -h'SEND {totals} *' command_totals = grep 'Total|Levels' show experience %-1
/def -i -h'SEND {<} *' command_< = kirahvi + say < $* %-1
/def -i -h'SEND {<} *' command_< = kirahvi + say < $* %-1
/def -i -h'SEND {mfinger} *' command_mfinger = finger $1 %-1
/def -i -h'SEND {ht} *' command_ht = hattrick+ say %-1
/def -i -h'SEND {?} *' command_? = show effects $* %-1
/def -i -h'SEND {say} *' command_say = cowsay -moose %-1
